#spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_service
#spring.datasource.username=root
#spring.datasource.password=1910
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#server.port=8080

#server.port=${PORT:8080}
#postgresql://bhanusri:zGCtdvp6LJWQxwqQZvGlOziQHKtud4Gj@/vehicledb_tvd3
#dpg-d6qith450q8c73bj97e0-a.oregon-postgres.render.com
#vehicledb_tvd3
#postgresql://dpg-d6qith450q8c73bj97e0-a.oregon-postgres.render.com/vehicledb_tvd3
#spring.datasource.url=jdbc:postgresql://dpg-d6qith450q8c73bj97e0-a.oregon-postgres.render.com:5432/vehicledb_tvd3
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=bhanusri
#spring.datasource.password=zGCtdvp6LJWQxwqQZvGlOziQHKtud4Gj



#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d6qith450q8c73bj97e0-a.oregon-postgres.render.com:5432/vehicledb_tvd3?sslmode=require
spring.datasource.username=bhanusri
spring.datasource.password=zGCtdvp6LJWQxwqQZvGlOziQHKtud4Gj
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}


